/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatePresence: typeof import('motion-v')['AnimatePresence']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarComponent: typeof import('./src/components/SidebarComponent.vue')['default']
  }
}
